Release workflow simplifications (#356)
* Release workflow simplifications

* doc

* Sync

* Remove prerelease support

* More

* Sync

* Fix

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,64 +3,88 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+  assemble:
+    uses: ./.github/workflows/reusable-assemble.yml
 
-      - name: Set up JDK for running Gradle
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: 17
+  test:
+    uses: ./.github/workflows/reusable-test.yml
 
-      - uses: gradle/gradle-build-action@v2
-        name: Build
-        with:
-          arguments: build
+  # test-latest-deps is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central
+  # it can fail due to test code incompatibility with the new library version,
+  # or due to slight changes in emitted telemetry
 
-      - uses: actions/upload-artifact@v3
-        name: Save unit test results
-        if: always()
-        with:
-          name: test-results
-          path: jmx-metrics/build/reports/tests/test
+  smoke-test:
+    uses: ./.github/workflows/reusable-smoke-test.yml
 
-  integration-test:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+  # muzzle is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central it can fail,
+  # and this is not a reason to hold up the release
 
-      - name: Set up JDK for running Gradle
-        uses: actions/setup-java@v3
-        with:
-          distribution: temurin
-          java-version: 17
+  gradle-plugins:
+    uses: ./.github/workflows/reusable-gradle-plugins.yml
 
-      - uses: gradle/gradle-build-action@v2
-        name: Integration test
-        with:
-          arguments: integrationTest
-
-      - uses: actions/upload-artifact@v3
-        name: Save integration test results
-        if: always()
-        with:
-          name: integration-test-results
-          path: jmx-metrics/build/reports/tests/integrationTest
+  examples:
+    uses: ./.github/workflows/reusable-examples.yml
 
   release:
-    runs-on: ubuntu-latest
     needs:
-      - build
-      - integration-test
+      - assemble
+      - test
+      - smoke-test
+      - gradle-plugins
+      - examples
+    runs-on: ubuntu-latest
     steps:
       - run: |
           if [[ $GITHUB_REF_NAME != release/* ]]; then
-            echo the release workflow should only be run against release branches
+            echo this workflow should only be run against release branches
             exit 1
           fi
 
+      - uses: actions/checkout@v3
+
+      - name: Set environment variables
+        run: |
+          version=$(.github/scripts/get-version.sh)
+          if [[ $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
+            major="${BASH_REMATCH[1]}"
+            minor="${BASH_REMATCH[2]}"
+            patch="${BASH_REMATCH[3]}"
+          else
+            echo "unexpected version: $version"
+            exit 1
+          fi
+          if [[ $patch == 0 ]]; then
+            if [[ $minor == 0 ]]; then
+              prior_major=$((major - 1))
+              prior_minor=$(grep -Po "^## Version $prior_major.\K[0-9]+" CHANGELOG.md | head -1)
+              prior_version="$prior_major.$prior_minor"
+            else
+              prior_version="$major.$((minor - 1)).0"
+            fi
+          else
+            prior_version="$major.$minor.$((patch - 1))"
+          fi
+          echo "VERSION=$version" >> $GITHUB_ENV
+          echo "PRIOR_VERSION=$prior_version" >> $GITHUB_ENV
+
+        # check out main branch to verify there won't be problems with merging the change log
+        # at the end of this workflow
+      - uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - run: |
+          if [[ $VERSION == *.0 ]]; then
+            # not making a patch release
+            if ! grep --quiet "^## Version $VERSION " CHANGELOG.md; then
+              echo the pull request generated by prepare-release-branch.yml needs to be merged first
+              exit 1
+            fi
+          fi
+
+        # back to the release branch
       - uses: actions/checkout@v3
         with:
           # tags are needed for the generate-release-contributors.sh script
@@ -82,30 +106,19 @@ jobs:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
 
-      - name: Set environment variables
-        run: |
-          version=$(.github/scripts/get-version.sh)
-          if [[ $version =~ ([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
-            major="${BASH_REMATCH[1]}"
-            minor="${BASH_REMATCH[2]}"
-            patch="${BASH_REMATCH[3]}"
-          else
-            echo "unexpected version: $version"
-            exit 1
-          fi
-          if [[ $patch == 0 ]]; then
-            if [[ $minor == 0 ]]; then
-              prior_major=$((major - 1))
-              prior_minor=$(grep -Po "^## Version $prior_major.\K([0-9]+)" CHANGELOG.md | head -1)
-              prior_version="$prior_major.$prior_minor"
-            else
-              prior_version="$major.$((minor - 1)).0"
-            fi
-          else
-            prior_version="$major.$minor.$((patch - 1))"
-          fi
-          echo "VERSION=$version" >> $GITHUB_ENV
-          echo "PRIOR_VERSION=$prior_version" >> $GITHUB_ENV
+      - name: Build and publish gradle plugins
+        uses: gradle/gradle-build-action@v2
+        env:
+          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
+          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
+          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
+          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
+        with:
+          # Don't use publishToSonatype since we don't want to publish the marker artifact
+          arguments: build publishPlugins publishPluginMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
+          build-root-directory: gradle-plugins
 
       - name: Generate release notes
         env:
@@ -124,17 +137,21 @@ jobs:
           EOF
           fi
 
+          # CHANGELOG_SECTION.md is also used at the end of the release workflow
+          # for copying the change log updates to main
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            > /tmp/CHANGELOG_SECTION.md
+
           # the complex perl regex is needed because markdown docs render newlines as soft wraps
           # while release notes render them as line breaks
-          sed -n "0,/^## Version $VERSION/d;/^## Version /q;p" CHANGELOG.md \
-            | perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' \
+          perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' /tmp/CHANGELOG_SECTION.md \
             >> /tmp/release-notes.txt
 
           # conditional block not indented because of the heredoc
           if [[ $VERSION == *.0 ]]; then
           cat >> /tmp/release-notes.txt << EOF
-
           ### 🙇 Thank you
+
           This release was possible thanks to the following contributors who shared their brilliant ideas and awesome pull requests:
 
           EOF
@@ -154,27 +171,117 @@ jobs:
                             v$VERSION \
                             opentelemetry-jmx-metrics.jar
 
-      - name: Update the change log with the release date
+      - uses: actions/checkout@v3
+        with:
+          # the step below is creating a pull request against main
+          ref: main
+
+      - name: Copy change log updates to main
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
-          sed -Ei "s/## Version $VERSION .*/## Version $VERSION ($date)/" CHANGELOG.md
+          if [[ $VERSION == *.0 ]]; then
+            # this was not a patch release, so the version exists already in the CHANGELOG.md
+
+            # update the release date
+            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+            sed -Ei "s/## Version $VERSION .*/## Version $VERSION ($date)/" CHANGELOG.md
+
+            # the entries are copied over from the release branch to support workflows
+            # where change log entries may be updated after preparing the release branch
+
+            # copy the portion above the release, up to and including the heading
+            sed -n "0,/^## Version $VERSION ($date)/p" CHANGELOG.md > /tmp/CHANGELOG.md
+
+            # copy the release notes
+            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
+
+            # copy the portion below the release
+            sed -n "0,/^## Version $VERSION /d;0,/^## Version /{/^## Version/!d};p" CHANGELOG.md \
+              >> /tmp/CHANGELOG.md
+
+            # update the real CHANGELOG.md
+            cp /tmp/CHANGELOG.md CHANGELOG.md
+          else
+            # this was a patch release, so the version does not exist already in the CHANGELOG.md
+
+            # copy the portion above the top-most release, not including the heading
+            sed -n "0,/^## Version /{ /^## Version /!p }" CHANGELOG.md > /tmp/CHANGELOG.md
+
+            # add the heading
+            date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+            echo "## Version $VERSION ($date)" >> /tmp/CHANGELOG.md
+
+            # copy the release notes
+            cat /tmp/CHANGELOG_SECTION.md >> /tmp/CHANGELOG.md
+
+            # copy the portion starting from the top-most release
+            sed -n "/^## Version /,\$p" CHANGELOG.md >> /tmp/CHANGELOG.md
+
+            # update the real CHANGELOG.md
+            cp /tmp/CHANGELOG.md CHANGELOG.md
+          fi
 
       - name: Set git user
         run: .github/scripts/set-git-user.sh
 
-      - name: Create pull request against the release branch
+      - name: Create pull request against main
         env:
-          # not using the default GITHUB_TOKEN because pull requests generated by it do not run any workflows
+          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
           GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
         run: |
-          message="Add the release date for $VERSION to the change log"
-          branch="add-release-date-for-${VERSION}"
+          message="Copy change log updates from $GITHUB_REF_NAME"
+          body="Copy log updates from \`$GITHUB_REF_NAME\`."
+          branch="copy-change-log-updates-from-${GITHUB_REF_NAME//\//-}"
+
+          if [[ $VERSION == *.0 ]]; then
+            if git diff --quiet; then
+              echo there are no updates needed to the change log on main, not creating pull request
+              exit 0 # success
+            fi
+          fi
 
           git commit -a -m "$message"
           git push origin HEAD:$branch
-          gh pr create --title "[$GITHUB_REF_NAME] $message" \
-                       --body "$message." \
+          gh pr create --title "$message" \
+                       --body "$body" \
                        --head $branch \
-                       --base $GITHUB_REF_NAME
+                       --base main
+
+      - uses: actions/checkout@v3
+        with:
+          repository: opentelemetry-java-bot/opentelemetry-operator
+          # this is the personal access token used for "git push" below
+          token: ${{ secrets.BOT_TOKEN }}
+
+      - name: Initialize pull request branch
+        run: |
+          git remote add upstream https://github.com/open-telemetry/opentelemetry-operator.git
+          git fetch upstream
+          git checkout -b update-opentelemetry-javaagent-to-${VERSION} upstream/main
+
+      - name: Update version
+        run: |
+          echo $VERSION > autoinstrumentation/java/version.txt
+
+      - name: Set git user
+        run: .github/scripts/set-git-user.sh
+
+      - name: Create pull request against opentelemetry-operator
+        env:
+          # this is the personal access token used for "gh pr create" below
+          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          message="Update the javaagent version to $VERSION"
+          body="Update the javaagent version to \`$VERSION\`."
+
+          # gh pr create doesn't have a way to explicitly specify different head and base
+          # repositories currently, but it will implicitly pick up the head from a different
+          # repository if you set up a tracking branch
+
+          git commit -a -m "$message"
+          git push --set-upstream origin update-opentelemetry-javaagent-to-${VERSION}
+          gh pr create --title "$message" \
+                       --body "$body" \
+                       --repo open-telemetry/opentelemetry-operator \
+                       --base main
